# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['app.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('templates', 'templates'),
        ('static', 'static'),
    ],
    hiddenimports=[
        'flask',
        'flask_login',
        'flask_login.utils',
        'flask_login.login_manager',
        'flask_login.mixins',
        'flask_login.signals',
        'flask_login.views',
        'flask_sqlalchemy',
        'werkzeug',
        'jinja2',
        'markupsafe',
        'click',
        'itsdangerous',
        'pandas',
        'numpy',
        'openpyxl',
        'requests',
        'apscheduler',
        'sqlalchemy',
        'chartjs',
        'bootstrap',
        'datatables',
        'pywin32_ctypes',
        'win32api',
        'win32con',
        'win32file',
        'win32com',
        'xhtml2pdf',
        'reportlab',
        'reportlab.graphics.barcode.code128',
        'reportlab.graphics.barcode.code39',
        'reportlab.graphics.barcode.code93',
        'reportlab.graphics.barcode.qr',
        'reportlab.graphics.barcode.usps',
        'reportlab.graphics.barcode.usps4s',
        'reportlab.graphics.barcode.eanbc',
        'reportlab.graphics.barcode.i2of5',
        'reportlab.graphics.barcode.ecc200datamatrix',
        'pywebview.platforms.winforms',
        'utils.api',
        'utils.helpers',
        'routes.auth',
        'routes.dashboard',
        'routes.api',
        'extensions',
        'models',
        'config',
        # Additional Flask-Login related imports
        'flask_login.__about__',
        'flask_login._compat',
        'flask_login.config',
        'flask_login.decorators',
        'flask_login.exceptions',
        'flask_login.password',
        'flask_login.recaptcha',
        'flask_login.test_client',
        'flask_login.unauthorized_handler',
        'flask_login.utils',
    ],
    hookspath=['./'],  # Look for hooks in the current directory
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='FPY_Dashboard',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)